pluginManagement {
    repositories {
        maven { url = uri(new File(rootDir, '.gradle-local/offline-plugin-repo')) }
        mavenCentral()
        gradlePluginPortal()
    }

    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'net.neoforged.moddev') {
                useModule('net.neoforged:moddev-gradle:2.0.141')
            }
        }
    }
}
