package com.hivesandcolonies.polen.entity.ai.debug;

import com.hivesandcolonies.polen.entity.ai.brain.mood.PolenMood;
import com.hivesandcolonies.polen.entity.ai.brain.intent.PolenIntent;
import com.hivesandcolonies.polen.entity.ai.navigation.search.PolenSearchStatus;
import com.hivesandcolonies.polen.entity.ai.navigation.search.PolenSearchType;
import com.hivesandcolonies.polen.entity.ai.brain.need.PolenNeed;
import com.hivesandcolonies.polen.entity.ai.brain.task.PolenTaskStatus;
import com.hivesandcolonies.polen.entity.ai.brain.task.PolenTaskType;
import com.hivesandcolonies.polen.entity.ai.world.affordance.PolenAffordanceType;
import com.hivesandcolonies.polen.entity.ai.world.home.PolenResidenceStage;
import com.hivesandcolonies.polen.entity.ai.world.comfort.PolenComfortRank;
import com.hivesandcolonies.polen.entity.ai.world.identity.PolenAffinity;
import com.hivesandcolonies.polen.entity.ai.world.interests.PolenInterest;
import com.hivesandcolonies.polen.entity.ai.world.story.PolenStoryStage;
import com.hivesandcolonies.polen.entity.ai.world.observation.PolenObservationDisposition;
import com.hivesandcolonies.polen.entity.ai.world.observation.PolenObservationFocus;
import net.minecraft.core.BlockPos;

import java.util.UUID;

public record PolenAiDebugSnapshot(
        PolenMood mood,
        String moodReason,
        PolenIntent intent,
        String intentReason,
        PolenTaskType task,
        PolenTaskType desiredTask,
        PolenTaskStatus taskStatus,
        String taskReason,
        String taskNote,
        PolenTaskType recentFailedTask,
        int recentFailureCount,
        long taskRecoverUntil,
        String quietActivity,
        PolenNeed dominantNeed,
        int safetyNeed,
        int socialNeed,
        int curiosityNeed,
        int restNeed,
        int magicNeed,
        boolean unsafeArea,
        boolean shouldSeekSafety,
        boolean shouldUseUnsafeDialogue,
        PolenSearchType searchType,
        PolenSearchStatus searchStatus,
        String searchNote,
        BlockPos searchTarget,
        BlockPos observedPos,
        PolenObservationFocus observationFocus,
        PolenObservationDisposition observationDisposition,
        PolenAffordanceType observationAffordanceType,
        BlockPos observationFocusPos,
        BlockPos observationUsePos,
        String observationContext,
        String observationNote,
        boolean nearRememberedInterest,
        BlockPos flowerSpot,
        BlockPos hiveSpot,
        BlockPos sourceSpot,
        BlockPos residenceAnchor,
        BlockPos residenceUse,
        String residenceContext,
        PolenResidenceStage residenceStage,
        int currentComfortScore,
        PolenComfortRank currentComfortRank,
        String currentComfortSummary,
        int residenceComfortScore,
        PolenComfortRank residenceComfortRank,
        String residenceComfortSummary,
        UUID worldIdentityId,
        UUID boundEntityUuid,
        PolenStoryStage storyStage,
        PolenInterest dominantInterest,
        PolenAffinity affinity,
        String equippedAffinityCharm,
        String interestSummary,
        String worldMemorySummary,
        BlockPos restingSpot,
        BlockPos dangerousSpot
) {
}
