package com.hivesandcolonies.hccharacters.character.polen.progression;

public enum PolenStoryFlag {

    NAME_REVEALED,
    CHAPTER_0_COMPLETE,
    PLAYER_HAS_SHELTER,

    POLEN_FOUND_FLOWER_SPOT,
    POLEN_FOUND_HIVE_SPOT,
    POLEN_FOUND_RESTING_SPOT,
    POLEN_FOUND_RESIDENCE,

    POLEN_MEMORY_FIRST_FLOWER,
    POLEN_MEMORY_FIRST_HIVE,
    POLEN_MEMORY_FIRST_SOURCE,
    POLEN_MEMORY_FIRST_COLONY,
    POLEN_MEMORY_FIRST_RESIDENCE

}
