# neoforge.mods.toml

modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"

issueTrackerURL="https://github.com/Williamhl2/HivesAndColonies-Polen/issues"

[[mods]] #mandatory

modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="Hives & Colonies: Characters" #mandatory

displayURL="https://www.curseforge.com/minecraft/mc-mods/hives-and-colonies-characters"
logoFile="hc_characters_logo.png"

authors="Williamhl2"

description='''
A story-driven NeoForge mod about meeting NPCs such as Polen,
earning their trust, and rebuilding the future of a lost kingdom.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="curios"
    type="required"
    versionRange="[9,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="sophisticatedbackpacks"
    type="required"
    versionRange="[3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="domum_ornamentum"
    type="required"
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"
